name: Deploy website to github pages


on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Installing Node
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - run: yarn
      - run: yarn run build
      - name: Deploying the website
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_REPO_TOKEN}}
